### PR TITLE
ISSUE-212 Improving method naming based on unique reference name instead of hardcoded ById

### PR DESCRIPTION
**Pull request by yuranos**
FYI: @stojsavljevic 
See #212 for details.

### CODE REVIEW

**Comment by yuranos** [comment]
@stojsavljevic , I found some parts of your commit related to #215 dubious. Let me come up with some corrections and we will review them together.

**Comment by yuranos** [comment]
@stojsavljevic , are we merging this one?

**Comment by stojsavljevic** [comment]
Please check my comment: https://github.com/phoenixnap/springmvc-raml-plugin/issues/212#issuecomment-351743153

**Comment by yuranos** [comment]
Sorry, missed it. Checking it now...

**Comment by stojsavljevic** [comment]
Can you please revert your changes in older raml test files - `issue-175.raml` and `issue-177.raml`?
Existing raml files are created to reproduce some resolved issue so we shouldn't change them. We can modify what is expected to be generated (`IssueXXX.java.txt`) but we must be careful so we don't re-introduce the issue.
If you want to cover more use cases for the issue you are resolving - add another `issue-212-X.raml`.

**Comment by yuranos** [comment]
@stojsavljevic , done. It's not a problem for me to add more tests, but 3 cases per issue should be fine, I think. I tested all the cases I was thinking about.

**Pull request merged**
