### PR TITLE
Modified the code to facilitate the below feature

### PR DESCRIPTION
**Pull request by ponprathip**
1.In the current form on raml to spring mvc stub creation it forces the plug-in to be run inside the maven project .I have done code changes to make it enable in both inside or external to maven project. I have tested and made sure the code changes are backward compatible .

### CODE REVIEW

**Comment by kurtpa** [comment]
Thanks for your commit - will be reviewing it asap :)

**Comment by kurtpa** [comment]
Looks,  good :)

**Comment by ponprathip** [comment]
Thanks .Hope it will be merged soon to master  for me to refer the main stream .

**Comment by ponprathip** [comment]
Can you please merge with the main stream .

**Pull request merged**
