### PR TITLE
Shortcut mapping annotations for Spring 4

### PR DESCRIPTION
**Pull request by yuranos**
@stojsavljevic , I haven't updated the REAMME yet, but I will need to resolve conflicts with the other PR before we can merge it.
So, for now, please provide your feedback. Thanks a lot!

### CODE REVIEW

**Comment by stojsavljevic** [comment]
Hi @yuranos,

this looks good from code perspective.

However, I don't think we should put much effort in polishing generated code.
Functionality of generated code is our top 1 priority and here you are adding shortcuts with exactly the same functionality - e.g. `@GetMapping` vs `@RequestMapping(method = RequestMethod.GET)`

Can you, please, in the future, open an issue first so we can discuss before you start working on a PR?
Thanks.

**Comment by yuranos** [comment]
Hi @stojsavljevic ,
Please, check the updated PR. I resolved conflicts and added README comment.

**Comment by stojsavljevic** [comment]
Can you add some tests please ?

**Comment by yuranos** [comment]
Hi mate,
Added a test.

**Comment by stojsavljevic** [comment]
The test is good because it uses a bit complex raml with headers and stuff.
But can you please add some dedicated test (like some `IssueXXXRulesTest` we have) that will cover all shortcut mappings you added?
We need good test coverage since it's the only way to properly test the code base.
Thanks mate!

**Comment by yuranos** [comment]
@stojsavljevic , added a specific test.

**Pull request merged**
