### PR TITLE
Replacing response entity with object

### PR DESCRIPTION
**Pull request by yuranos**
@stojsavljevic , another suggestion. Why do we want to keep ResponseEntity<?> if we decide to go with a non-wrapped types? In the implementation we can still return ResponseEntity if we want, but we might go for something different.

### CODE REVIEW

**Comment by stojsavljevic** [comment]
@yuranos how is this PR related to previous one?

**Comment by yuranos** [comment]
I'd rather merge #196 first. They are related but not dependent on each other.

**Comment by yuranos** [comment]
Amended text files since noticed that I accidentally replaced {project.version} placeholders.

**Comment by yuranos** [comment]
@stojsavljevic , can we merge this one?

**Comment by stojsavljevic** [comment]
After some thinking, I'm not sure.

I agree that having plain objects is a cleaner solution.
But on the other hand, `ResponseEntity` gives you ability to control response status and response headers. So we would lose this with the PR.
What is your motivation for this PR?

Sorry for writing this after you did the coding, but as I said on some other PR, it's better to start with an issue so we can discuss it before actual work.

**Comment by yuranos** [comment]
Hi @stojsavljevic ,
No worries, this one wasn't that complicated. With Object return type you can still return whatever you want including ResponseEntity. It just gives more flexibility. What's more - no one restricts you from putting a more exact return type in the implementation. I can have Object in the interface and narrow it down to ResponseType in the implementation.

**Comment by stojsavljevic** [comment]
In my mind it gives too much flexibility so it's more error prone.

I would rather introduce configuration option and default to existing functionality.

**Comment by yuranos** [comment]
Ok, will do.

**Comment by yuranos** [comment]
@stojsavljevic , please check.

**Comment by yuranos** [comment]
@stojsavljevic, let's merge this one before validation. I'm tired of resolving conflicts. The last one will be the most important.

**Comment by stojsavljevic** [comment]
@yuranos 

After looking at your changes I don't think we need new configuration option for this.
In my mind, if `simpleReturnTypes` is `true` we should always generate `Object` in case that return type is not specified.
Sorry because I misled you. I was probably confused with purpose of this PR.

Also, I noticed that `SpringSimpleResponseTypeRule` looks different the PR but on your branch, like there are different versions. Can you also check?

**Comment by yuranos** [comment]
@stojsavljevic , please check now.
I'm not sure what you meant by 

> Also, I noticed that SpringSimpleResponseTypeRule looks different in the PR but on your branch, like they are different versions.
I didn't change it at all. Only some accidental whitespaces.

**Comment by stojsavljevic** [comment]
Can you please revert your changes in `SpringSimpleResponseTypeRule` since you didn't add real changes and I will recheck?
Also, please, remove `objectForUnspecifiedReturnType` from `README.md`.
Thanks.

**Comment by yuranos** [comment]
@stojsavljevic , done. I use spaces instead of tabs, that's why I have these issues.

**Pull request merged**
