### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by Boskiantonio**
Changes which i needed for my project which use springmvc-raml-plugin. Maybe they will be useful for you:
1. Support for multipart file.
2. Creating directory when it does not exists. Useful when generating in target dir.
3. I removed "required" from @PathVariable because it always is required.
4. Generating List as response in interface strategy was missing.

### CODE REVIEW

**Comment by kurtpa** [comment]
Thanks for taking the time to improve this project! will check it out and merge asap :)

**Comment by kurtpa** [comment]
The additional properties enabling is going to change the default behaviour of the plugin a bit too significantly. Kindly either remove this from the PR or make it off by default and configurable on/off. Other than that we're good to merge :)

**Comment by Boskiantonio** [comment]
Well it wasn't my intention to add this change to pull request. I didnt expect that my commit from today will be automatically added to it. I was going to make it configurable in the future. Either way i remove this chage for now.

**Comment by kurtpa** [comment]
Thank you! :)

**Pull request merged**
