### PR TITLE
Feature/#1 add support for raml 1.0 step1 decoupling

### PR DESCRIPTION
**Pull request by aweisser**
The PR provides a decoupling from `org.raml.model` as a first step towards an adaption of other raml parsers (like `raml-parser-2`). 

The abstraction is located in package `com.phoenixnap.oss.ramlapisync.raml`. Any dependency to `org.raml.model` is bound to package `com.phoenixnap.oss.ramlapisync.raml.rjp.raml08v1`.

So if we want to support other raml parsers (like Raml Java Parser V2 for RAML Spec. v0.8 or V1.0) we just need to provide another adapter (for example `raml08v2 `or `raml1v2`).

The `RamlModelFactoryOfFactories` just returns a `RJP08V1RamlModelFactory` for now, because this is just a refactoring. The class should be more intelligent in the future, when we started to provide adapters to `raml-parser-2`.

The whole PR is (hopefully) a behavoir preserving refactoring.
The current master is merged and all tests are green.
But we can't be 100% sure, because the code coverage is not 100%....

So perhaps it should be considered as BETA...

### CODE REVIEW

**Comment by kurtpa** [comment]
Thanks Armin!

I'll release 0.7.2 which has a bugfix, then i'll merge this. I have some test files and controller that i can use to test a bit more

**Comment by kurtpa** [comment]
Thanks Armin!

There are some missing Javadoc & License headers, i'll add these so that we can merge this refactor asap to master

**Comment by aweisser** [comment]
Ok. Thanks Kurt. 
Sorry for not having javadocs and license headers included in the PR. I'll try to work on that anti pattern ... ;)

**Comment by aweisser** [comment]
Currently I'm working on adapting raml-parser-2 for raml spec 0.8. Should I raise a new Issue for this second step? Or should we do all the steps until Raml v1.0 support in this very same issue ?

**Comment by kurtpa** [comment]
No worries re javadoc!
I think we can reuse this issue :)

**Pull request merged**
