### PR TITLE
Issue - 193 - @Valid support in Intefrace

### PR DESCRIPTION
**Pull request by yuranos**

### CODE REVIEW

**Comment by yuranos** [comment]
@stojsavljevic , this is what I wanted, but I found a big problem in Spring MVC itself: https://jira.spring.io/browse/SPR-11055
In any case, for my idea to work, we will probably need to pass jsr property from mojo to the rules, which will require a base Rule interface change.
I also found there's a bug in the way @Valid is added to a body:
`	@Override
    protected JVar paramObjects(ApiActionMetadata endpointMetadata, CodeModelHelper.JExtMethod generatableType) {
        JVar param = super.paramObjects(endpointMetadata, generatableType);
		if (!RamlActionType.PATCH.equals(endpointMetadata.getActionType())) {
			// skip Valid annotation for PATCH actions since it's a partial
			// update so some required fields might be omitted
			param.annotate(Valid.class);
		}
        param.annotate(RequestBody.class);
        return param;
    }`
If you look at this snippet - there's no check for the property from mojo, so @Valid is always generated for a body.

Another thing:
Can someone explain how code like this:
`		if (paramMetaData.getRamlParam().getMinimum() != null) {
			jVar.annotate(Min.class).param("value", paramMetaData.getRamlParam().getMinimum().longValue());
		}
		if (paramMetaData.getRamlParam().getMaximum() != null) {
			jVar.annotate(Max.class).param("value", paramMetaData.getRamlParam().getMaximum().longValue());
		}`
works inside MethodParamsRule.paramQueryForm?
Are validation annotations added directly to the method signature? If so, again, they need to be enabled somehow, and it seems it's not happening.

**Comment by yuranos** [comment]
@stojsavljevic, I, however, found a workaround for annotation inheritance. We need to use @Validated on the interface. You already use this annotation, but only for stubs. Let's add it to an interface!
Should I proceed with both:

1. Adding @Validated to interface;
2. Passing jsr to Rule
?

**Comment by yuranos** [comment]
Hi, @stojsavljevic!
I found a way that works for me. Let me know what you think, and if it works for you, I'll fix tests.

**Comment by yuranos** [comment]
Some observations: I played around with @Max on a method parameter and @Validated on a class.
1) If @Validated is placed in only 1 place, either Interface or Class, all is good.
2) @Validated on Interface, @Max in Class - HV000151 error.
3) @Validated on both, @Max on Class - HV000151 error.
4) @Validated on both, @Max on Interface - works!
5) @Validated on Interface, @Max on Class - HV000151 error.
6) @Validated on Interface, @Max on Interface - works!
7) 2 identical @Max work!(Regardless of @Validated place)
8) @Validated on Class, @Max on Interface - works!
9) @Max should have identical config.

**Comment by stojsavljevic** [comment]
Hi @yuranos,

Thanks for your work.

Adding `@Validated` on interface is perfectly fine.

But I don't think you should remove `@Valid` annotation from method signature.
Bean validation will not be kicked off without it.

**Comment by stojsavljevic** [comment]
And regarding `Min` and `Max` annotations - take a look at the test related to issue 175.

**Comment by yuranos** [comment]
Hi, @stojsavljevic, I personally tested all the scenarios I mentioned in the previous post and I can guarantee you it will work.
Moreover, as I explained, based on https://jira.spring.io/browse/SPR-11055, @Valid annotation on interface doesn't make any sense.
Let me check body parameters one more time. I will get back to you shortly if I find something suspicious.

**Comment by stojsavljevic** [comment]
Consider this example:

```
#%RAML 1.0
title: XXX

types: 
  SiteKey:
    properties: 
      site: 
        type: string
      no: 
        type: number
        minimum: 5
        maximum: 10

/test:
  post:
    body: 
      application/json:
        type: SiteKey
```

and generate code using `Spring4ControllerDecoratorRule`.
Then call the endpoint with something like:
```
{"site":"google.com","no":3}
```
I tried this with your code and the validation doesn't work.

TBH, it doesn't work properly with the existing code - `@Valid` is required on the interface as well.

**Comment by yuranos** [comment]
@stojsavljevic , you were right. One of my test cases was wrong. It is true that validation on Controllers behaves a bit different than on regular beans, because of a more complicated lifecycle(found a bit of info in [here](https://stackoverflow.com/questions/19425221/spring-validated-in-service-layer)), so for example on Controller I can use `@Validatted` on a class and then `@Validated` on a method param, and the validation is triggered, but it's not the case for other beans and obviously not a way to do it unless a validation against a specific group is required.
In any case, it is wrong to expect validation from a method without annotations, so I reverted that part where I deleted `@Valid`.

**Comment by yuranos** [comment]
@stojsavljevic , please merge if everything is Ok.

**Comment by stojsavljevic** [comment]
Why does this PR has title "Issue 65" when #65 is about Gradle plugin?

**Comment by yuranos** [comment]
Oh, sorry, that was a typo. Sure, let me know if you have further questions.

**Comment by stojsavljevic** [comment]
Hey man! Thanks for your work.

But I have one suggestion - let's make this solution works for all types of code generation.

We need to make sure that:
* this works for rules: `Spring4ControllerStubRule`, `Spring4ControllerDecoratorRule` and `Spring4ControllerInterfaceRule`
* all validation related annotations are under control of `includeJsr303Annotations` parameter

Ideally, we should have validation related annotations on interface only in case that interface is generated. But there is `Spring4ControllerStubRule` that doesn't generate interface. So for that rule we should have validation on actual controller. If that complicates the work - I'm perfectly fine with having validation related annotations on both interface and implementation.

**Comment by stojsavljevic** [comment]
One small tip: part of the code for adding `@Valid` on method parameter should probably be moved from `SpringMethodParamsRule` to `MethodParamsRule` so that way `@Valid` will be added on both interface and implementation.
As I stated in the previous comment - not ideal solution but we can live with it.
Also, `includeJsr303Annotations` should be taken into consideration when adding `@Valid`.

**Comment by yuranos** [comment]
Hi @stojsavljevic ,

Please check my last commit.
Now validation annotations are generated based on jsr303 plugin config. I have some concerns:

1. I don't like the fact that we pass an object of type `PojoGenerationConfig` into API generating rules.

2. FeignClient doesn't have validation annotations at all. Before adding them to it, I'd like to know if it actually works the way it's expected to for Feign. I didn't manage to find any solid documentation on that.

**Comment by yuranos** [comment]
By the way, `Spring4ControllerStubRule` was always dependent on this code: `.addClassAnnotationRule(new SpringValidatedClassAnnotationRule())` so it contained @Validated even without my changes.

**Comment by stojsavljevic** [comment]
Holy moly, I didn't expect that checking generation config will introduce that many changes.

Can you please revert your latest changes and ignore my statement:
> all validation related annotations are under control of includeJsr303Annotations parameter

Also, ignore `FeignClient` as well in terms of validation. 

I plan to restructure the plugin and one of my priorities will be to simplify the config and the way we are reading it. Passing a config object is not the way to go.
Once I come out with the plan for restructuring I will invite you @yuranos to participate.

**Comment by yuranos** [comment]
@stojsavljevic , done via revert. Want to keep it in history. There were some interesting parts in it. All remaining PRs are also updated based on your comments.

**Comment by yuranos** [comment]
Strange. My branch has a couple of conflicts with master, but it is not identified by github. @stojsavljevic do you know how this is possible?

**Comment by yuranos** [comment]
Should be good now, @stojsavljevic

**Comment by stojsavljevic** [comment]
Found 2 issues:

- `@Valid` is not added on interface in case of `Spring4ControllerDecoratorRule` which leads to infamous `HV000151` error. IMHO, you should use `SpringMethodParamsRule` instead of `MethodParamsRule` when generating interface inside `SpringControllerDecoratorRule`
- can you please revert your changes in `SpringMethodParamsRule` because they are only format related

**Comment by yuranos** [comment]
Another try, @stojsavljevic

**Comment by yuranos** [comment]
@stojsavljevic , updated from master.

**Comment by yuranos** [comment]
@stojsavljevic, can we merge it now?

**Pull request merged**
