### PR TITLE
Support of jsonschema2pojo configuration

### PR DESCRIPTION
**Pull request by ellavas**
Proposition to fix issue #45

### CODE REVIEW

**Comment by kurtpa** [comment]
Hi!

Thanks for taking the time to write this enhancement - just a couple of minor changes before i can merge the PR.

1. Kindly fix version to 0.6.0 (we have not yet started using the SNAPSHOT convention :))
2. Kindly change license of added files to the Apache Software Foundation license
3. Please pull changes from master into your branch and merge

Thanks again!

Kurt

**Comment by ellavas** [comment]
Done :)

**Comment by kurtpa** [comment]
Thanks, i'll look into it asap :D

**Comment by kurtpa** [comment]
Merged, thanks!

**Pull request merged**
