### PR TITLE
Add uriPrefix parameter during Verifying against Implementation

### PR DESCRIPTION
**Pull request by tsarnowski**
During generating code from RAML file it is posible to specify
baseUri which is used as prefix for all generated resources.
But this prefix breaks verificaiton against implementation
so add parameter which can compensate baseUri during code
generation.

### CODE REVIEW

**Comment by kurtpa** [comment]
Hiya - thanks for taking the time to improve this project - i'll be reviewing your changes asap :)

**Comment by kurtpa** [comment]
Hiya, 

i just reviewed this implementation - this same functionality can be achieved in less risky ways, such as by fast forwarding in the RamlVerifier/RamlCheckers

I'm really sorry but i'll be declining this PR in it's current state and will be implementing your functionality in the verification stage

**Comment by tsarnowski** [comment]
When You suppose to add this functionality ? In 1-2 weeks or later?

**Comment by kurtpa** [comment]
Less than 2weeks, I'll try get it done next weekend :)

**Pull request closed without merging**
