### PR TITLE
Fix issue #67: Optionally add HttpHeaders parameter in methods

### PR DESCRIPTION
**Pull request by tofcoder**
Proposal to fix issue #67. The approach used for testing is quite brutal (basically copy/paste of existing tests). Let me know if there is a better way.

### CODE REVIEW

**Comment by aweisser** [comment]
Imho copy pasting test is better than having conditional tests.

**Comment by aweisser** [comment]
Except my comment on paramsRule the code looks fine to me. You'll become the pr king of the month :)

**Comment by tofcoder** [comment]
Thanks for your comment. Code is far cleaner like this.

**Comment by kurtpa** [comment]
Thanks for taking the time to implement and review this @tofcoder @aweisser 

I have only 2 points:
  - We need to also Update the README.md to reflect the new configuration parameter in the Mojo
  - My initial concern is that we are adding this injection variable in the model at an action level (ApiActionMetadata), when currently is only configurable globally. I don't mind starting off like this but if we see that we are not going to add features to control this in a more fine grained way (eg, only show headers for certain resources/calls) then we need to move it outwards, at least to the ResourceLevel, or even better make the MethodParamRule a ConfigurableRule and then pass it in as a parameter

Any thoughts before i merge this?

**Comment by tofcoder** [comment]
@kurtpa Would be nice to have a new release on Maven Central that includes this change, and the other expected features and bug fixes.

**Comment by kurtpa** [comment]
definitely - on my todo list for today :)

**Pull request merged**
